[package]
name = "leetcode"
version = "1.0.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rstest = "0.18"
proptest = "1.4"
lazy_static = "1.4"
rand = "0.8"
spectral = "0.6"
criterion = "0.5"
